name: s3-rmq-ack-demo

services:
  producer:
    build:
      context: ../..
      dockerfile: services/producer/Dockerfile
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-1c-exchange}
      MINIO_REGION: us-east-1

      AMQP_URL: amqp://${RMQ_USER:-guest}:${RMQ_PASS:-guest}@haproxy:5672/
      RMQ_EXCHANGE: ex.msg
      RMQ_ROUTING_KEY: branch1
      RMQ_QUEUE: q.branch1
    depends_on:
      minio:
        condition: service_healthy
      haproxy:
        condition: service_healthy

  branch_consumer:
    build:
      context: ../..
      dockerfile: services/branch_consumer/Dockerfile
    environment:
      MINIO_ENDPOINT: http://minio:9000
      MINIO_ACCESS_KEY: ${MINIO_ACCESS_KEY:-minioadmin}
      MINIO_SECRET_KEY: ${MINIO_SECRET_KEY:-minioadmin}
      MINIO_BUCKET: ${MINIO_BUCKET:-1c-exchange}
      MINIO_REGION: us-east-1

      AMQP_URL: amqp://${RMQ_USER:-guest}:${RMQ_PASS:-guest}@haproxy:5672/
      RMQ_EXCHANGE: ex.msg
      RMQ_ROUTING_KEY: branch1
      RMQ_QUEUE: q.branch1
      RMQ_ACK_EXCHANGE: ex.ack
      RMQ_ACK_ROUTING_KEY: ack
      RMQ_ACK_QUEUE: q.ack

      CONSUMER_ID: branch1
      PREFETCH: "10"
    depends_on:
      minio:
        condition: service_healthy
      haproxy:
        condition: service_healthy

  coordinator:
    build:
      context: ../..
      dockerfile: services/coordinator/Dockerfile
    environment:
      AMQP_URL: amqp://${RMQ_USER:-guest}:${RMQ_PASS:-guest}@haproxy:5672/
      RMQ_ACK_EXCHANGE: ex.ack
      RMQ_ACK_ROUTING_KEY: ack
      RMQ_ACK_QUEUE: q.ack
      RMQ_POINTER_EXCHANGE: ex.msg
      RMQ_POINTER_ROUTING_KEY: branch1
      RMQ_POINTER_QUEUE: q.pointer
      PREFETCH: "50"
      DB_DSN: postgresql://ack:ackpass@postgres:5432/ackdb
      S3_ENDPOINT: http://minio:9000
      S3_ACCESS_KEY: minioadmin
      S3_SECRET_KEY: minioadmin

    depends_on:
      haproxy:
        condition: service_healthy

